---
- name: add Caddy repo
  become: true
  apt_repository:
    repo: deb [trusted=yes] https://apt.fury.io/caddy/ /
    filename: caddy-fury.list
    state: present

- name: install Caddy
  become: true
  apt:
    name: caddy
    update_cache: true

- name: copy Caddyfile
  become: true
  copy:
    src: files/Caddyfile
    dest: /etc/caddy/Caddyfile
    mode: '0644'

- name: systemd service
  become: true
  template:
    src: caddy.service
    dest: /etc/systemd/system/caddy.service
    owner: root
    group: root
    mode: 0644

- name: allow server to bind to port
  become: true
  shell: setcap CAP_NET_BIND_SERVICE=+eip $(which caddy)

- name: restart caddy
  become: true
  systemd:
    name: caddy
    state: restarted